# clairgrid : data structuration, presentation and navigation.
# Copyright David Lambert 2025

FROM node:alpine3.22
WORKDIR /usr/src/clairgrid/web-ui
CMD ["sh", "-c", "npm install -g npm@11.6.4 && npm i -D @sveltejs/adapter-node && npm run dev -- --host"]