# clairgrid : data structuration, presentation and navigation.
# Copyright David Lambert 2025

FROM pypy:3.11-7
WORKDIR /usr/src/clairgrid/grid-service
RUN apt-get update && apt-get install -y libpq5 && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["tail", "-f", "/dev/null"]