# clairgrid : data structuration, presentation and navigation.
# Copyright David Lambert 2025

FROM pypy:3.10
WORKDIR /usr/src/clairgrid/grid-service
RUN apt-get update && apt-get install -y libpq5 && rm -rf /var/lib/apt/lists/*
COPY * .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["watchmedo", "auto-restart", "--patterns=*.py", "--recursive", "--", "pypy3", "grid_service.py"]