# clairgrid : data structuration, presentation and navigation.
# Copyright David Lambert 2025

# This file contains the Development Dockerfile for the clairgrid Grid Service.

FROM python:3.11.14
WORKDIR /usr/src/clairgrid/grid-service
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["watchmedo", "auto-restart", "--patterns=*.py", "--recursive", "--", "python", "grid_service.py"]