# clairgrid : data structuration, presentation and navigation.
# Copyright David Lambert 2025

FROM python:3.14.2
WORKDIR /usr/src/clairgrid/grid-service
COPY * .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["watchmedo", "auto-restart", "--patterns=*.py", "--recursive", "--", "python", "grid_service.py"]